# Navigation Links
#   The weight parameter defines the order that the links will appear in.

main:
  - name: Home
    weight: 10
    identifier: Home
  - name: About
    url: '#about'
    weight: 11
    parent: Home
  - name: Manual for Contributors
    url: https://manual.dataobservatory.eu/
    weight: 12
    parent: Home
  - name: Terms & Conditions
    url: ../terms
    weight: 13
    parent: Home
  - name: News
    weight: 20
    identifier: News
  - name: Blog
    url: ../post/
    weight: 22
    parent: News
  - name: Topics
    url: '#tags'
    weight: 23
    parent: News  
  - name: Solutions
    url: '#services'
    weight: 30
    identifier: Solutions
  - name: Apps
    url: 'apps/'
    weight: 31
    parent: Solutions
  - name: Software
    url: '#releases'
    weight: 32
    parent: Solutions
  - name: Code
    url: '/category/r-bloggers/'
    weight: 34
    parent: Solutions
  - name: Data
    url: '#pillars'
    weight: 40
    identifier: Data
  - name: 🏛️ Music & Economy
    url: https://music.dataobservatory.eu/pillar/music-economy/
    weight: 41
    parent: Data
  - name: 🏛️ Diversity & Circulation
    url: https://music.dataobservatory.eu/pillar/diversity-circulation/
    weight: 42
    parent: Data
  - name: 🏛️ Music & Society
    url: https://music.dataobservatory.eu/pillar/music-and-society/
    weight: 43
    parent: Data
  - name: 🏛️ Music Tech & Innovation
    url: https://music.dataobservatory.eu/pillar/innovation/
    weight: 44
    parent: Data
  - name: 📖 Open Science Repository
    url: 'https://zenodo.org/communities/music_observatory'
    weight: 48
    parent: Data
  - name: GO FAIR
    url: https://www.go-fair.org/fair-principles/fairification-process/
    parent: Data
  - name: Resources
    url: ../resources/
    weight: 59
    identifier: Resources
  - name: Overview
    url: ../resources/
    weight: 60
    parent: Resources
  - name: Manual for Contributors
    url: https://manual.dataobservatory.eu/
    weight: 61
    parent: Resources
  - name: Open Policy Analysis Guidelines
    url: ../resources/opa/
    weight: 62
    parent: Resources
  - name: WP1 Music Economy
    url: ../resources/report-european-music-economy/
    weight: 63
    parent: Resources
  - name: WP2 Diversity & Circulation
    url: ../resources/report-music-diversity-circulation/
    weight: 64
    parent: Resources
  - name: WP3 Music Society & Citizenship
    url: ../resources/report-music-society-citizenship/
    weight: 65
    parent: Resources
  - name: WP4 Innovation & Tech
    url: ../resources/report-music-innovation-tech/
    weight: 66
    parent: Resources
  - name: WP5 Open Music Observatory
    url: ../resources/open-music-observatory/
    weight: 66
    parent: Resources
#    url: '#publications'
#    weight: 62
#    parent: Publications
  - name: Consortium
    url: '#contributors'
    weight: 80
    identifier: Consortium
  - name: Contact
    url: '#contact'
    weight: 90
    identifier: Contact
  - name: Get in touch
    url: '#contact'
    weight: 91
    parent: Contact
  - name: Public talks
    url: '#talks'
    weight: 92
    parent: Contact
